spring:
  active:
    profile: "test"
  application:
    name: jfpersonalapi
  datasource:
    url: jdbc:h2:mem:testes
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

