spring:
  application:
    name: jfpersonalapi
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL}
#  jdbc:postgresql://dpg-d489uem3jp1c73cf8j20-a:5432/jfpersonaldb
