# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: CI buil e testes com maven

on:
  push:
    branches:
      - '**'     # executa em todas as branches
  pull_request:
    branches:
      - '**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build e Tests com Maven
      run: mvn clean verify
